apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: arachni
  name: arachni
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      io.kompose.service: arachni
  strategy: {}
  template:
    metadata:
      annotations: {}
      creationTimestamp: {}
      labels:
        io.kompose.service: arachni
    spec:
      containers:
        - args:
            - bin/arachni_rest_server
            - --address
            - 0.0.0.0
          image: ahannigan/docker-arachni
          imagePullPolicy: ""
          name: arachniscanner
          ports:
            - containerPort: 9292
            - containerPort: 7331
          resources: {}
      restartPolicy: { { .Values.restartPolicy } }
      serviceAccountName: {}
      volumes: {}
status: {}
