{{- if .Values.arachni.deployment.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: {{ include "arachni.name" . }}-arachni
    helm.sh/chart: {{ include "arachni.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "arachni.fullname" . }}-arachni
spec:
  ports:
    - name: "9292"
      port: 9292
      targetPort: 9292
    - name: "7331"
      port: 7331
      targetPort: 7331
  selector:
    app.kubernetes.io/name: {{ include "arachni.name" . }}-arachni
    helm.sh/chart: {{ include "arachni.chart" . }}
status:
  loadBalancer: {}
{{- end -}}