apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: arachni
  name: arachni
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: arachni
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: arachni
    spec:
      containers:
      - args:
        - bin/arachni_rest_server
        - --address
        - 0.0.0.0
        image: ahannigan/docker-arachni
        imagePullPolicy: ""
        name: arachniscanner
        ports:
        - containerPort: 9292
        - containerPort: 7331
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
