apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: arachni
  name: arachni
spec:
  ports:
  - name: "9292"
    port: 9292
    targetPort: 9292
  - name: "7331"
    port: 7331
    targetPort: 7331
  selector:
    io.kompose.service: arachni
status:
  loadBalancer: {}
