apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: archerysec-worker
  name: archerysec-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: archerysec-worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: archerysec-worker
    spec:
      containers:
      - env:
        - name: ARCHERY_WORKER
          value: "True"
        - name: DB_HOST
          value: db
        - name: DB_NAME
          value: archerysec
        - name: DB_PASSWORD
          value: archerysec
        - name: DB_USER
          value: archerysec
        - name: DJANGO_DEBUG
          value: "1"
        - name: DJANGO_SECRET_KEY
          value: '"SETME"'
        - name: DJANGO_SETTINGS_MODULE
          value: archerysecurity.settings.development
        - name: EMAIL_HOST
          value: mailhog
        - name: EMAIL_PORT
          value: "1025"
        image: archerysec/archerysec
        imagePullPolicy: ""
        name: archerysec-worker
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
