{{- if .Values.mailhog.deployment.enabled -}}
{{- if .Values.mailhog.ingress.enabled -}}
{{- $fullName := include "mailhog.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "mailhog.name" . }}
    helm.sh/chart: {{ include "mailhog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.mailhog.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.mailhog.ingress.tls }}
  tls:
  {{- range .Values.imailhog.ngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- with .secretName }}
      secretName: {{ . }}
      {{- end }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.mailhog.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
        {{- end }}
  {{- end }}
{{- end }}
{{- end -}}