{{- if .Values.mailhog.deployment.enabled -}}
{{- if and (.Values.mailhog.auth.enabled) (not .Values.mailhog.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "mailhog.name" . }}
    helm.sh/chart: {{ include "mailhog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ template "mailhog.authFileSecret" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.mailhog.auth.fileName }}: {{ .Values.mailhog.auth.fileContents | b64enc }}
{{- end -}}
{{- end -}}