apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: openvas
  name: openvas
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  - name: "9390"
    port: 9390
    targetPort: 9390
  - name: "9392"
    port: 9392
    targetPort: 9392
  selector:
    io.kompose.service: openvas
status:
  loadBalancer: {}
