{{- if .Values.openvas.deployment.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvas.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "openvas.name" . }}
    helm.sh/chart: {{ include "openvas.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "443"
    port: {{ .Values.openvas.ports.https_web }}
    targetPort: {{ .Values.openvas.ports.https_web }}
  - name: "9390"
    port: {{ .Values.openvas.ports.api_1 }}
    targetPort: {{ .Values.openvas.ports.api_1 }}
  - name: "9392"
    port: {{ .Values.openvas.ports.api_2 }}
    targetPort: {{ .Values.openvas.ports.api_2 }}
  selector: {}
status:
  loadBalancer: {}
{{- end -}}