apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "archerysec.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""] # " " indicates core API groups
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list"]
