{{- if .Values.zaproxy.deployment.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "zaproxy.name"}}-service
    helm.sh/chart: {{ include "arachni.chart" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namepsace }}
  name: {{ include "zaproxy.fullname" . }}
spec:
  ports:
  - name: "{{ .Values.zaproxy.service.api_port }}"
    port: {{ .Values.zaproxy.service.api_port }}
    targetPort: {{ .Values.zaproxy.service.api_port }}
  selector:
    mathLabels:
      app.kubernetes.io/name: {{ include "zaproxy.name" }}
      app.kubernetes.io/instance: {{ .Release.Name }}
status:
  loadBalancer: {}
{{- end -}}