{{- if .Values.zaproxy.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zaproxy.fullname" .}}
  labels:
    app.kubernetes.io/name: {{ include "zaproxy.name" . }}
    helm.sh/chart: {{ include "zaproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zaproxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.zaproxy.podAnnotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "zaproxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{ with .Values.zaproxy.podlabels }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        command: ["/bin/sh"]
        args: ["-c", "zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true"]
        image: "{{ .Values.zaproxy.image }}:{{ .Values.zaproxy.tag }}"
        imagePullPolicy: "{{ .Values.zaproxy.imagePullPolicy }}"
        name: {{ template "zaproxy.name" . }}
        ports:
          - containerPort: {{ .Values.zaproxy.service.api_port }}
        resources:
          {{- toYaml .Values.zaproxy.resources | nindent 8 -}}
      restartPolicy: {{ .Values.zaproxy.restartPolicy }}
      serviceAccountName: {}
      volumes: {}
status: {}
{{- end -}}