apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zaproxy
  name: zaproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zaproxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: zaproxy
    spec:
      containers:
      - args:
        - zap.sh
        - -daemon
        - -host
        - 0.0.0.0
        - -port
        - "8090"
        - -config
        - api.disablekey=true
        - -config
        - api.addrs.addr.name=.*
        - -config
        - api.addrs.addr.regex=true
        image: owasp/zap2docker-stable
        imagePullPolicy: ""
        name: zapscanner
        ports:
        - containerPort: 8090
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
